    // Mapear para o formato ExtractedResult
    const mappedLeads: ExtractedResult[] = rawLeads.map((r: any) => ({
      name: r.name || 'Contato atuante',
      phone: r.phone || '',
      email: r.email || '',
      instagram: r.instagram || '',
      location: r.location || cleanLocation || 'Brasil',
      profileUrl: r.sourceUrl || '',
      platform: 'facebook' as PlatformType,
      entityType: 'pj',
      category: r.category || r.source || 'Prospecção Ativa',
      company: r.company || r.grupo || 'Grupo Facebook',
      department: r.department || 'Mercado Agro',
      decisionMaker: r.decisionMaker || 'Contato atuante',
      pitchRecommendation: r.pitchRecommendation || `📌 Enviar link do site para ${r.name} — contato atuante no mercado.`,
      trendingInsights: Array.isArray(r.trendingInsights) ? r.trendingInsights : (r.intent ? [r.intent.substring(0, 200)] : []),
      competitorPrices: '',
      demandTimeframe: r.demandTimeframe || 'Últimos 60 dias',
      rating: r.rating || 5,
      reviewsCount: r.reviewsCount || 0,
      confidence: r.confidence || r.score || 70,
      // Campos extras que o card também mostra
      whatsapp: r.phone || '',
      establishmentPhone: r.phone || '',
      decisionMakerPhone: r.phone || '',
      legalSource: r.legalSource || 'Origem: Facebook Groups (Prospecção Ativa)',
      cnpj: '',
    }));
